---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
```

```{r}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  sample_n(5000) %>% 
 separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax) / 10,
    tmin = as.numeric(tmin) / 10,
    snow_mm = snow,
    snow = round(snow_mm * 0.03937 * 4) / 4)

 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa %>% 
  mutate(text_label = str_c(year)) %>% 
  plot_ly(
    x = ~tmin, y = ~snwd, color = ~year, text = ~text_label, 
          type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa %>%
  group_by(year) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE),
            mean_tmin = mean(tmin, na.rm = TRUE)) %>% 
  mutate(text_label = str_c("Max Temp: ", mean_tmax)) %>% 
  plot_ly(
    x = ~year, y = ~mean_tmin, color = ~year, text =  ~text_label,
    type = "bar", colors = "viridis"
  )
  
```

### Chart C

```{r}
ny_noaa %>%
  mutate(text_label = str_c("Year ", year)) %>% 
  plot_ly(
    x = ~month, y = ~prcp, color = ~month, text = ~text_label,
    type = "box", colors = "viridis"
  )

```


