---
title: "Sushupta Vijapur"
output: 
  html_document:
    toc: true
    toc_float: true
---


#### MPH Candidate - Epidemiology and Applied Biostatistics 
#### Columbia University Mailman School of Public Health


## Education

I graduated from The [University of Pittsburgh](http://neuroscience.pitt.edu/) in 2018 with a BS in Neuroscience and a minor in Chemistry. After taking a year off to work, I started at [Columbia University Mailman School of Public Health](https://www.publichealth.columbia.edu/academics/departments/epidemiology), studying Epidemiology and Applied Biostatistics.

## Hobbies and Interests

I have always enjoying drawing and painting. I fell away from this hobby for years but picked it up again during quarantine. I love spicy food and reading in coffee shops. I also enjoy hiking with my golden doodle (pictured above) and am unfortunately a NY Giants fan. 


## Contact Information

[Department of Epidemiology](https://www.publichealth.columbia.edu/academics/departments/epidemiology)\
Columbia University Mailman School of Public Health\
722 West 168th Street\
New York, New York 10032\
Email: smv2138@columbia.edu\
Phone: 908-635-7448